/****************************************************************
 *                                                              *
 * Copyright (c) Nuvoton Technology Corp. All rights reserved.  *
 *                                                              *
 ****************************************************************/

#ifndef __PLATFORM_INC__
#define __PLATFORM_INC__


#include "../../HW/Include/SFR.inc"		/* H/W SFR definition */

#define	__NUVOTON__						/* Nuvoton platform */


#endif /* __PLATFORM_INC__ */

